# Generated by Django 4.2.26 on 2025-11-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_adminprofile_id_remove_course_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='participants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.DeleteModel(
            name='LiveClassAttendance',
        ),
    ]
