# Generated by Django 5.2.6 on 2025-12-06 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_announcement_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC-5', max_length=50)),
                ('dashboard_view', models.CharField(choices=[('default', 'Default'), ('courses', 'Courses'), ('calendar', 'Calendar'), ('analytics', 'Analytics')], default='default', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('inapp_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('notify_assignments', models.BooleanField(default=True)),
                ('notify_grades', models.BooleanField(default=True)),
                ('notify_announcements', models.BooleanField(default=True)),
                ('notify_reminders', models.BooleanField(default=True)),
                ('notify_discussion_replies', models.BooleanField(default=False)),
                ('notify_student_submissions', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('private', 'Private')], default='public', max_length=20)),
                ('email_visible', models.BooleanField(default=False)),
                ('phone_visible', models.BooleanField(default=False)),
                ('allow_messaging', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('auto_enrollment', models.BooleanField(default=False)),
                ('deadline_reminders', models.BooleanField(default=True)),
                ('late_submission_warning', models.BooleanField(default=True)),
                ('default_grading_scheme', models.CharField(choices=[('percentage', 'Percentage'), ('letter', 'Letter Grade'), ('points', 'Points')], default='percentage', max_length=20)),
                ('late_submission_policy', models.CharField(choices=[('no_penalty', 'No Penalty'), ('partial_credit', 'Partial Credit'), ('no_credit', 'No Credit')], default='partial_credit', max_length=20)),
                ('course_visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20)),
                ('plagiarism_check', models.BooleanField(default=True)),
                ('student_messaging', models.BooleanField(default=True)),
                ('user_registration', models.BooleanField(default=True)),
                ('course_approval', models.BooleanField(default=False)),
                ('system_maintenance', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('password_policy', models.CharField(choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], default='strong', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='participants',
        ),
    ]
