# Generated by Django 4.2.7 on 2025-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usersettings_remove_liveclass_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=10),
        ),
    ]
