# Generated by Django 5.2.6 on 2025-12-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_courseschedule'),
        ('core', '0013_update_assignment_status'),
    ]

    operations = [
    ]
