# Generated by Django 4.2.7 on 2026-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_announcement_dispatched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='library_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue')], default='active', max_length=20),
        ),
    ]
